### PR TITLE
Introduced a fix for a hash key collision when using just query ID as…

### PR DESCRIPTION
**Pull request by artyomtkachenko**
… a key

Hi Phillip,

I faced the same problem as described in [#8](https://github.com/Phillipmartin/gopassivedns/issues/8) and spent some time to fix it by changing the key from just query ID to a combination src port -> dest Port:query ID. We deployed this change in prod and it looks really good.  

Could you please review my changes when you get a chance?

Regards,
Artyom

### CODE REVIEW

**Comment by Phillipmartin** [comment]
Thanks!  I worry a little about the perf impact of the use of strings for this PR.  Did you do any perf testing before and after the patch?  is there some other transform we could do that avoids the string conversions but still fixes the problem?

**Comment by artyomtkachenko** [comment]
Thanks for a quick reply. 

I was considering to stay in the uint32/int64 space, but decided to try and to first  go with a simple concatenation. The idea was to rely on a very efficient hashing function in Go itself rather than implementing/using any other algorithm. 

I did a canary deployment on one of our servers and  was monitoring our performance metrics for a few hours. I didn't notice any performance degradation at all (or it was very insignificant).

**Comment by Phillipmartin** [comment]
Cool.  I'll run my benchmark suite and make sure it looks good before I merge.  Should have time this weekend

**Comment by Phillipmartin** [comment]
@artyomtkachenko I'm good with this.  Unfortunately I just merged in a change from another contributor that created some conflicts.  could you rebase and I'll merge?

**Comment by artyomtkachenko** [comment]
Hi @Phillipmartin ,

My apologies for a long delay for this one. I have finally managed to find some time and  do a rebase. I also changed the key type from string to int64 + did some minor performance enchantments which reduced CPU usage by ~ 10%

**Pull request merged**
